### ISSUE TITLE
Update Marketing Website For 2022 Event Window

### ISSUE THREAD

**Issue by SGGregory** [code-newbies/codeland#118]
# Description of Task

We'll need to update the CodeLand marketing site (codelandconf.com) in preparation for CodeLand 2022 to go live on Thursday, June 16.

Ideally, all of these changes would go live on the site today _except for the prominent banner, which would go live tomorrow at 8 AM PT/11 AM ET. 

## Task List 

- [ ] **Remove Tracy Chou announcement banner** — Original issue [here](https://github.com/code-newbies/codeland/issues/106)

- [ ] **Create prominent banner up top that directs people to [day-of site](https://community.codenewbie.org/codeland)**

_Copy can say:_ **CodeLand 2022 is here! [>> Enter event portal](https://community.codenewbie.org/codeland).**
 
_Note: I think it's fine if we use the same style as we've had for the keynote announcement banner updates, but I think the text should be larger._

- [ ] Replace `CodeLand 2021` Top Menu option with `Schedule & Event Portal` option that links to [day-of site](https://community.codenewbie.org/codeland)
- [ ] **Change language under** `Attend` **section to say the following:**

`**Attend**`
`**CodeLand 2022 is taking place right now (June 16-17) from 9am-3pm PT / 12-6pm ET / 4-10pm UTC. Go check it out [here](https://community.codenewbie.org/codeland) while you can! The full CodeLand 2022 experience is only available to those who register, which you can do via the link below.**`

---

### _Note: I have a question for @abbyphoenix about possible changes to our registration options. I will initiate a discussion in the comments below and will then replace this text with formal requests for that once we arrive at them._

**Comment by SGGregory** [comment]
@abbyphoenix  what do you think about registration? I think we should leave reg open through the end of the event/midday through Day 2? Curious to hear your thoughts. 

Also, curious to hear your thoughts on the overall timing of these changes going live (see `Description of Task` section)

**Comment by danieltott** [comment]
@SGGregory the codeland 2021 link is linking to last years conference - are we removing that for clarity?

**Comment by danieltott** [comment]
My two cents is that if someone wants to attend, they'll hit the giant "enter event portal" link and skip registering... I'd replace the "register" button with the "schedule and event portal" and remove the registration section...

**Comment by abbyphoenix** [comment]
I'm fine with leaving registration (aka **Attend**) up, but I would maybe change the language under the Attend section to clarify. Instead of 

> **Attend**
CodeLand 2022 is an entirely remote two-day conference. Each day will be six hours long (9am-3pm PT / 12-6pm ET / 4-10pm UTC) and will consist of a mix of keynotes, live speaker panels, pre-recorded talks, and engaging activities.

Maybe something like:

>**Attend**
CodeLand 2022 is taking place right now (June 16-17) from 9am-3pm PT / 12-6pm ET / 4-10pm UTC. While you can go check it out [here](https://community.codenewbie.org/codeland), the full CodeLand 2022 experience is only available to those who register, which you can do at the link below!

**Comment by abbyphoenix** [comment]
I totally hear what @danieltott's saying too, and I agree regarding the probable behavior, but I do think that there will be some folks who realize that they can't win prizes and stuff without having registered, so there's an argument there for leaving registration up for those who want to then come back and then register?

**Comment by abbyphoenix** [comment]
Timing sounds fine to me!

**Comment by danieltott** [comment]
@SGGregory @abbyphoenix here's the deploy preview: https://deploy-preview-120--codelandconf.netlify.app/

**Comment by SGGregory** [comment]
This looks great! I'm good to go with this as it appears in the preview tomorrow! Thanks for the quick turnaround, @danieltott!

**Comment by abbyphoenix** [comment]
@SGGregory Thoughts on the copy change suggestion under **Attend**?

**Comment by SGGregory** [comment]
@abbyphoenix this works! I'll add the suggested language it to the main issue up top @danieltott

**Comment by danieltott** [comment]
> Ideally, all of these changes would go live on the site today _except for the prominent banner, which would go live tomorrow at 8 AM PT/11 AM ET.

Are there any changes that should still go up today?

**Comment by danieltott** [comment]
Attend text updated in the deploy preview 👍🏼

**Comment by SGGregory** [comment]
> > Ideally, all of these changes would go live on the site today _except for the prominent banner, which would go live tomorrow at 8 AM PT/11 AM ET.
> 
> Are there any changes that should still go up today?

All changes but the big banner can go up today whenever/as soon as is convenient for you! Banner can go live tomorrow at 8 AM PT/11 AM ET. Should these have been in a separate issue because of that? Sorry if so :(
